export const PromptSuggestions = () => [
  {
    prompts: [
      "Show a rotating cube with changing colors",
      "Animate the Pythagorean theorem with a right triangle",
      "Draw a circle that transforms into a square",
      "Create multiple squares arranged in a grid pattern",
      "Show a polygon morphing through different shapes",
      "Animate a spiral forming from the center",
      "Draw a hexagon and show its properties",
      "Visualize the equation E = mc²",
      "Show the quadratic formula step by step",
      "Animate a sine wave moving across the screen",
      "Graph a parabola with equation y = x²",
      "Show the sum of angles in a triangle",
      "Demonstrate the Fibonacci sequence with squares",
      "Visualize pi (π) with a circle",
      "Show fraction addition with visual blocks",
      "Show bubble sort with colored bars",
      "Animate a binary tree structure",
      "Visualize array insertion and deletion",
      "Show a linked list with nodes and pointers",
      "Demonstrate stack push and pop operations",
      "Animate queue enqueue and dequeue",
      "Animate sorting algorithms comparing bubble sort vs quicksort",
      "Show recursive function calls as a tree",
      "Show a pendulum swinging back and forth",
      "Animate a bouncing ball with gravity",
      "Visualize vector addition with arrows",
      "Show projectile motion of an object",
      "Demonstrate Newton's second law F = ma",
      "Animate circular motion with velocity vectors",
      "Create an animated title that writes itself",
      "Show text fading in and out with colors",
      "Display a quote with typewriter effect",
      "Animate text transforming into different words",
      "Show bullet points appearing one by one",
      "Create a loading spinner animation",
      "Show three circles moving in a pattern",
      "Animate a square rotating around a circle",
      "Create a simple progress bar filling up",
      "Show dots appearing in sequence",
      "Animate arrows pointing in different directions",
    ],
  },
];
